apiVersion: v1
kind: ConfigMap
metadata:
  name: verqo-api-config
  namespace: {{ .Values.namespace }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.api.env.aspnetcoreEnvironment | quote }}
  ASPNETCORE_URLS: "http://+:{{ .Values.api.port }}"
  Cors__AllowedOrigins__0: {{ .Values.api.env.corsAllowedOrigins | quote }}
  Jwt__Issuer: {{ .Values.api.env.jwtIssuer | quote }}
  Jwt__Audience: {{ .Values.api.env.jwtAudience | quote }}
