using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Verqo.Infrastructure.Migrations;

/// <summary>
/// Creates the full schema: users, verification_checks, freelancer_profiles,
/// client_profiles, jobs, proposals, contracts, milestones, ledger_entries,
/// payouts, invoices, messages, reviews, disputes — one table per
/// Verqo.Domain.Entities type, matching VerqoDbContext.OnModelCreating
/// exactly (table names, the enum-as-string conversion, FK delete
/// behaviours, and the two 1:1 unique-FK relationships on Milestone).
///
/// Written by hand rather than generated by `dotnet ef migrations add`:
/// this sandbox's network egress can't reach api.nuget.org (same
/// restriction as the rest of Verqo.Infrastructure/Verqo.Api — see
/// docs/ARCHITECTURE.md §7), so the EF Core Design package needed for the
/// scaffolding tool isn't available here. What IS available — a real local
/// PostgreSQL 16 instance — was used to genuinely verify this Up() SQL:
/// applied cleanly, then a full users → profiles → job → contract →
/// milestone → ledger_entries insert chain round-tripped through every
/// foreign key without error. See the CI job added to
/// .github/workflows/dotnet.yml, which re-verifies this migration for real
/// (a Postgres service container + `dotnet ef database update`) and checks
/// this migration's Designer.cs/ModelSnapshot.cs actually match the live
/// model — the one part of this that couldn't be verified in this sandbox.
/// </summary>
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE users (
                "Id" uuid NOT NULL,
                "Email" text NOT NULL,
                "PasswordHash" text NOT NULL,
                "Role" text NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_users" PRIMARY KEY ("Id")
            );
            CREATE UNIQUE INDEX "IX_users_Email" ON users ("Email");

            CREATE TABLE verification_checks (
                "Id" uuid NOT NULL,
                "UserId" uuid NOT NULL,
                "Stage" text NOT NULL,
                "Result" text NOT NULL,
                "PartnerReference" text NULL,
                "CheckedAt" timestamp with time zone NULL,
                "RequiresHumanReview" boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_verification_checks" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_verification_checks_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX "IX_verification_checks_UserId_Stage" ON verification_checks ("UserId", "Stage");

            CREATE TABLE freelancer_profiles (
                "Id" uuid NOT NULL,
                "UserId" uuid NOT NULL,
                "DisplayName" text NOT NULL,
                "Headline" text NULL,
                "Bio" text NULL,
                "PrimaryRole" text NOT NULL,
                "RateBand" text NULL,
                "ExperienceLevel" text NULL,
                "HourlyRateMinor" integer NULL,
                "PanNumber" text NOT NULL,
                "PanVerificationResult" text NOT NULL,
                "PanVerifiedAt" timestamp with time zone NULL,
                "PanVerificationReference" text NULL,
                "AadhaarLast4" text NOT NULL,
                "AadhaarHash" text NOT NULL,
                "AadhaarVerificationResult" text NOT NULL,
                "AadhaarVerifiedAt" timestamp with time zone NULL,
                "AadhaarVerificationReference" text NULL,
                "EpfUanLast4" text NULL,
                "EpfActiveStatusResult" text NOT NULL,
                "EpfCheckedAt" timestamp with time zone NULL,
                "EpfVerificationReference" text NULL,
                "BankAccountVerifiedAt" timestamp with time zone NULL,
                "BankDetailChangedAt" timestamp with time zone NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_freelancer_profiles" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_freelancer_profiles_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX "IX_freelancer_profiles_UserId" ON freelancer_profiles ("UserId");
            CREATE INDEX "IX_freelancer_profiles_AadhaarHash" ON freelancer_profiles ("AadhaarHash");

            CREATE TABLE client_profiles (
                "Id" uuid NOT NULL,
                "UserId" uuid NOT NULL,
                "CompanyName" text NOT NULL,
                "Gstin" text NULL,
                "Plan" text NOT NULL,
                "NegotiatedFeeRate" double precision NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_client_profiles" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_client_profiles_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX "IX_client_profiles_UserId" ON client_profiles ("UserId");

            CREATE TABLE jobs (
                "Id" uuid NOT NULL,
                "ClientId" uuid NOT NULL,
                "Title" text NOT NULL,
                "Description" text NOT NULL,
                "Channel" text NOT NULL,
                "RoleCategory" text NOT NULL,
                "BudgetMinorMin" integer NULL,
                "BudgetMinorMax" integer NULL,
                "Status" text NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_jobs" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_jobs_client_profiles_ClientId" FOREIGN KEY ("ClientId") REFERENCES client_profiles ("Id") ON DELETE CASCADE
            );
            CREATE INDEX "IX_jobs_ClientId" ON jobs ("ClientId");

            CREATE TABLE proposals (
                "Id" uuid NOT NULL,
                "JobId" uuid NOT NULL,
                "FreelancerId" uuid NOT NULL,
                "CoverNote" text NOT NULL,
                "ProposedRateMinor" integer NOT NULL,
                "Status" text NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_proposals" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_proposals_jobs_JobId" FOREIGN KEY ("JobId") REFERENCES jobs ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_proposals_freelancer_profiles_FreelancerId" FOREIGN KEY ("FreelancerId") REFERENCES freelancer_profiles ("Id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX "IX_proposals_JobId_FreelancerId" ON proposals ("JobId", "FreelancerId");
            CREATE INDEX "IX_proposals_FreelancerId" ON proposals ("FreelancerId");

            CREATE TABLE contracts (
                "Id" uuid NOT NULL,
                "JobId" uuid NULL,
                "ClientId" uuid NOT NULL,
                "FreelancerId" uuid NOT NULL,
                "Channel" text NOT NULL,
                "ScopeSummary" text NOT NULL,
                "Status" text NOT NULL,
                "IntroducedAt" timestamp with time zone NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_contracts" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_contracts_jobs_JobId" FOREIGN KEY ("JobId") REFERENCES jobs ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_contracts_client_profiles_ClientId" FOREIGN KEY ("ClientId") REFERENCES client_profiles ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_contracts_freelancer_profiles_FreelancerId" FOREIGN KEY ("FreelancerId") REFERENCES freelancer_profiles ("Id") ON DELETE CASCADE
            );
            CREATE INDEX "IX_contracts_JobId" ON contracts ("JobId");
            CREATE INDEX "IX_contracts_ClientId" ON contracts ("ClientId");
            CREATE INDEX "IX_contracts_FreelancerId" ON contracts ("FreelancerId");

            CREATE TABLE milestones (
                "Id" uuid NOT NULL,
                "ContractId" uuid NOT NULL,
                "Title" text NOT NULL,
                "ContractValueMinor" integer NOT NULL,
                "State" text NOT NULL,
                "ReviewWindowDays" integer NOT NULL,
                "RevisionsAllowed" integer NOT NULL,
                "RevisionsUsed" integer NOT NULL,
                "FundedAt" timestamp with time zone NULL,
                "SubmittedAt" timestamp with time zone NULL,
                "ReviewDeadlineAt" timestamp with time zone NULL,
                "ReleasedAt" timestamp with time zone NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_milestones" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_milestones_contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES contracts ("Id") ON DELETE CASCADE
            );
            CREATE INDEX "IX_milestones_ContractId" ON milestones ("ContractId");

            CREATE TABLE ledger_entries (
                "Id" uuid NOT NULL,
                "MilestoneId" uuid NOT NULL,
                "Type" text NOT NULL,
                "AmountMinor" integer NOT NULL,
                "Currency" text NOT NULL,
                "IdempotencyKey" text NOT NULL,
                "ReversesEntryId" uuid NULL,
                "GatewayReference" text NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_ledger_entries" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_ledger_entries_milestones_MilestoneId" FOREIGN KEY ("MilestoneId") REFERENCES milestones ("Id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX "IX_ledger_entries_IdempotencyKey" ON ledger_entries ("IdempotencyKey");
            CREATE INDEX "IX_ledger_entries_MilestoneId" ON ledger_entries ("MilestoneId");

            CREATE TABLE payouts (
                "Id" uuid NOT NULL,
                "MilestoneId" uuid NOT NULL,
                "Rail" text NOT NULL,
                "Status" text NOT NULL,
                "AmountMinor" integer NOT NULL,
                "Utr" text NULL,
                "AttemptedAt" timestamp with time zone NOT NULL,
                "SettledAt" timestamp with time zone NULL,
                CONSTRAINT "PK_payouts" PRIMARY KEY ("Id")
            );

            CREATE TABLE invoices (
                "Id" uuid NOT NULL,
                "MilestoneId" uuid NOT NULL,
                "InvoiceNumber" text NOT NULL,
                "GstAmountMinor" integer NOT NULL,
                "TotalMinor" integer NOT NULL,
                "IssuedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_invoices" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_invoices_milestones_MilestoneId" FOREIGN KEY ("MilestoneId") REFERENCES milestones ("Id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX "IX_invoices_MilestoneId" ON invoices ("MilestoneId");
            CREATE UNIQUE INDEX "IX_invoices_InvoiceNumber" ON invoices ("InvoiceNumber");

            CREATE TABLE messages (
                "Id" uuid NOT NULL,
                "ContractId" uuid NOT NULL,
                "SenderId" uuid NOT NULL,
                "Body" text NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_messages" PRIMARY KEY ("Id")
            );
            CREATE INDEX "IX_messages_ContractId" ON messages ("ContractId");

            CREATE TABLE reviews (
                "Id" uuid NOT NULL,
                "ContractId" uuid NOT NULL,
                "AuthorId" uuid NOT NULL,
                "Rating" integer NOT NULL,
                "Comment" text NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_reviews" PRIMARY KEY ("Id")
            );

            CREATE TABLE disputes (
                "Id" uuid NOT NULL,
                "MilestoneId" uuid NOT NULL,
                "RaisedById" uuid NOT NULL,
                "Reason" text NOT NULL,
                "EvidenceDeadline" timestamp with time zone NOT NULL,
                "DecisionDeadline" timestamp with time zone NOT NULL,
                "Outcome" text NULL,
                "DecidedAt" timestamp with time zone NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_disputes" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_disputes_milestones_MilestoneId" FOREIGN KEY ("MilestoneId") REFERENCES milestones ("Id") ON DELETE CASCADE
            );
            CREATE UNIQUE INDEX "IX_disputes_MilestoneId" ON disputes ("MilestoneId");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TABLE disputes;
            DROP TABLE reviews;
            DROP TABLE messages;
            DROP TABLE invoices;
            DROP TABLE payouts;
            DROP TABLE ledger_entries;
            DROP TABLE milestones;
            DROP TABLE contracts;
            DROP TABLE proposals;
            DROP TABLE jobs;
            DROP TABLE client_profiles;
            DROP TABLE freelancer_profiles;
            DROP TABLE verification_checks;
            DROP TABLE users;
            """);
    }
}
